const questions = [
  {
    id: 1,
    question:
      "Para retornar múltiplos itens em uma função render de um componente React é necessário encapsular o retorno de todos os itens em uma única saída e por isso existe o Fragment, que irá se comportar da seguinte forma:",
    answer: "Irá adicionar somente os itens internos ao DOM sem nenhum encapsulamento.",
    options: [
      "Encapsular todos em uma div para manter a semântica do HTML.",
      "Encapsular todos em um elemento <> para manter a semântica do HTML.",
      "Encapsular todos em um span para manter a semântica do HTML.",
      "Irá adicionar somente os itens internos ao DOM sem nenhum encapsulamento.",
    ],
    topic: "Frontend",
    difficulty: "easy",
  },
  {
    id: 2,
    question:
      "Ao usar o CSS Grid Layout para dispor os elementos de um interface, nós podemos deixar que o próprio grid conduza o posicionamento dos itens dentro do espaço em disposição através do seu auto-placement, porém existe uma propriedade que permite controlar como eles irão se organizar e esta seria:",
    answer: "grid-auto-flow",
    options: ["grid-direction", "grid-auto-flow", "grid-orientation", "grid-axis"],
    topic: "Frontend",
    difficulty: "easy",
  },
  {
    id: 3,
    question: "Em qual tipo de memória fica armazenada as informações que são utilizadas pela API de Clipboard do HTML5?",
    answer: "Data Buffer",
    options: ["Data Buffer", "Disk Buffer", "Write Buffer", "Circular Buffer"],
    topic: "Frontend",
    difficulty: "hard",
  },
  {
    id: 4,
    question:
      "Qual a métrica utilizada para identificar o tempo que leva entre a primeira visualização de um elemento de uma página web e o momento que o seu conteúdo pode receber inputs dos usuários?",
    answer: "Total Blocking Time",
    options: ["Total Blocking Time", "First Content Paint", "First Input Delay", "Time to Interactive"],
    topic: "Frontend",
    difficulty: "medium",
  },
  {
    id: 5,
    question:
      "Qual propriedade de um item dentro de um container com display:flex define a capacidade do mesmo ocupar menos espaço caso necessário?",
    answer: "flex-shrink",
    options: ["flex-flow", "flex-grow", "flex-wrap", "flex-shrink"],
    topic: "Frontend",
    difficulty: "medium",
  },
  {
    id: 6,
    question:
      "Qual a melhor forma para atualizar em tela mudanças em tempo real para usuários de uma plataforma web que não estão utilizando a aplicação no momento?",
    answer: "Notifications API",
    options: ["Websockets", "Server Side Events", "Notifications API", "Local Notification"],
    topic: "Frontend",
    difficulty: "medium",
  },
  {
    id: 7,
    question: "Qual evento do Window responsável por notificar qualquer janela que houve uma mudança em qualquer dado de sua localStorage?",
    answer: "storage",
    options: ["hashchange", "keychange", "storage", "popchange"],
    topic: "Frontend",
    difficulty: "medium",
  },
  {
    id: 8,
    question: "Qual dos seguintes data types do Javascript não é primitivo?",
    answer: "Number",
    options: ["Object", "Number", "Null", "Boolean"],
    topic: "Frontend",
    difficulty: "medium",
  },
  {
    id: 9,
    question: "Como garantir que não haverá mudanças nos valores de um objeto o tornando imutável com Javascript?",
    answer: "Utilizar a função nativa Object.freeze",
    options: [
      "Utilizar a função nativa Object.seal",
      "Declarar o objeto usando const",
      "Declarar o objeto usando let",
      "Utilizar a função nativa Object.freeze",
    ],
    topic: "Frontend",
    difficulty: "medium",
  },
  {
    id: 10,
    question: "Qual a maneira de voltar o histórico de navegação do usuário para 3 páginas atrás?",
    answer: "History.go(-3)",
    options: ["History.back(3)", "History.replaceState(3)", "History.pushState(-3)", "History.go(-3)"],
    topic: "Frontend",
    difficulty: "medium",
  },
  {
    id: 11,
    question: "Qual das seguintes características é relacionada a uma Standard Queue da AWS SQS?",
    answer: "At-Least-Once Delivery",
    options: ["High Throughput", "Exactly-Once Processing", "First-In-First-Out Delivery", "At-Least-Once Delivery"],
    topic: "AWS",
    difficulty: "easy",
  },
  {
    id: 12,
    question: "Qual das seguintes engines não é suportada pelo serviço Amazon RDS?",
    answer: "SQLite",
    options: ["MariaDB", "Oracle", "PostgreSQL", "SQLite"],
    topic: "AWS",
    difficulty: "easy",
  },
  {
    id: 13,
    question: "Qual dos seguintes produtos da AWS não é um serviço de computação?",
    answer: "Route53",
    options: ["EC2", "Route53", "Lambda", "ECS"],
    topic: "AWS",
    difficulty: "easy",
  },
  {
    id: 14,
    question:
      "Qual o conceito do CloudFront é utilizado para disponibilizar conteúdos personalizados baseados na localização na qual a plataforma está sendo acessada?",
    answer: "Geo Targeting",
    options: ["AWS Regions", "Availability Zones", "Geo Targeting", "Geolocation"],
    topic: "AWS",
    difficulty: "easy",
  },
  {
    id: 15,
    question: "Qual o número máximo de IP elásticos numa única conta da AWS consegue gerar?",
    answer: "5",
    options: ["5", "3", "10", "1"],
    topic: "AWS",
    difficulty: "hard",
  },
  {
    id: 16,
    question: "Qual a flag é necessária para poder editar o conteúdo do último commit realizado?",
    answer: "--amend",
    options: ["--edit", "--rewrite", "--amend", "--patch"],
    topic: "Git",
    difficulty: "easy",
  },
  {
    id: 17,
    question: "Qual das opções de merge de duas branches irá gerar um novo commit com a integração entre as branches?",
    answer: "three way",
    options: ["rebase", "three way", "fast foward", "fetch"],
    topic: "Git",
    difficulty: "easy",
  },
  {
    id: 18,
    question: "Como pegar os itens do seu stash e não removê-los ao serem adicionados no seu working directory?",
    answer: "git stash apply",
    options: ["git stash drop", "git stash pop", "git stash apply", "git stash save"],
    topic: "Git",
    difficulty: "easy",
  },
  {
    id: 19,
    question: "Como buscar branches que possuem um commit em específico?",
    answer: "git branch --contains COMMIT_HASH",
    options: [
      "git branch --list COMMIT_HASH",
      "git commit --list COMMIT_HASH",
      "git commit --contains COMMIT_HASH",
      "git branch --contains COMMIT_HASH",
    ],
    topic: "Git",
    difficulty: "hard",
  },
  {
    id: 20,
    question: "Usando o git bisect para buscar um bug, como marcar o commit que introduziu o erro?",
    answer: "git bisect bad",
    options: ["git bisect apply", "git bisect broken", "git bisect save", "git bisect bad"],
    topic: "Git",
    difficulty: "hard",
  },
  {
    id: 21,
    question: "Qual o tipo de serviço Kubernetes é utilizado para ser exposto na internet?",
    answer: "Load Balancer",
    options: ["Cluster IP", "Node Port", "External Name", "Load Balancer"],
    topic: "Kubernetes",
    difficulty: "hard",
  },
  {
    id: 22,
    question: "Qual o comando usado para rodar um comando em um container específico com o kubectl?",
    answer: "kubectl exec",
    options: ["kubectl run", "kubectl apply", "kubectl exec", "kubectl attach"],
    topic: "Kubernetes",
    difficulty: "hard",
  },
  {
    id: 23,
    question: "Como interromper um container imediatamente com o docker?",
    answer: "docker kill CONTAINER_ID",
    options: ["docker kill CONTAINER_ID", "docker stop CONTAINER_ID", "docker prune CONTAINER_ID", "docker pause CONTAINER_ID"],
    topic: "Docker",
    difficulty: "hard",
  },
  {
    id: 24,
    question: "Qual das seguintes opções não é o status de um container?",
    answer: "Killed",
    options: ["Killed", "Created", "Running", "Paused"],
    topic: "Docker",
    difficulty: "hard",
  },
  {
    id: 25,
    question: "Qual dos seguintes data types do Python não é IMUTÁVEL?",
    answer: "List",
    options: ["Bytes", "List", "Number", "Tuple"],
    topic: "Python",
    difficulty: "hard",
  },
  {
    id: 26,
    question: "Qual o último nível de escopo é verificado em busca de uma declaração pelo interpretador Python?",
    answer: "Built-in",
    options: ["Local", "Built-in", "Global", "Module"],
    topic: "Python",
    difficulty: "hard",
  },
  {
    id: 27,
    question: "Como converter um número inteiro para string em Python?",
    answer: "str()",
    options: ["to_string()", "str()", "string()", "String.valueOf()"],
    topic: "Python",
    difficulty: "hard",
  },
  {
    id: 28,
    question: "Em Orientação a Objetos, quando uma classe base é herdada por diversas classes derivadas nós chamamos isso de:",
    answer: "Hierarchical Inheritance",
    options: ["Multilevel Inheritance", "Hierarchical Inheritance", "Multiple Inheritance", "Single Inheritance"],
    topic: "Arquitetura",
    difficulty: "hard",
  },
  {
    id: 29,
    question: "O que é um paradigma de programação?",
    answer: "Uma abordagem ou estilo de programação baseado em um conjunto de princípios ou conceitos fundamentais",
    options: [
      "Um tipo de linguagem de programação",
      "Uma forma de codificar que não segue padrões",
      "Um conjunto de bugs comuns em programação",
      "Uma abordagem ou estilo de programação baseado em um conjunto de princípios ou conceitos fundamentais",
    ],
    topic: "Paradigmas de Programação",
    difficulty: "easy",
  },
  {
    id: 30,
    question: "Qual a diferença entre HTTP e HTTPS?",
    answer: "O HTTPS é uma versão segura do HTTP, que utiliza criptografia para garantir a segurança da comunicação",
    options: [
      "O HTTPS é mais rápido que o HTTP",
      "O HTTP é uma versão segura do HTTPS",
      "O HTTP não é mais usado hoje em dia",
      "O HTTPS é uma versão segura do HTTP, que utiliza criptografia para garantir a segurança da comunicação",
    ],
    topic: "Segurança na Web",
    difficulty: "hard",
  },
  {
    id: 31,
    question: "O que é o Git?",
    answer: "Um sistema de controle de versão distribuído",
    options: [
      "Um banco de dados relacional",
      "Um ambiente de desenvolvimento integrado",
      "Um sistema de gerenciamento de projetos",
      "Um sistema de controle de versão distribuído",
    ],
    topic: "Git",
    difficulty: "easy",
  },
  {
    id: 32,
    question: "O que é uma linguagem de programação orientada a objetos?",
    answer: "Uma linguagem de programação que usa objetos como unidades básicas para modelar dados e funcionalidades",
    options: [
      "Uma linguagem de programação que não usa objetos",
      "Uma linguagem de programação que usa funções como unidades básicas para modelar dados e funcionalidades",
      "Uma linguagem de programação que usa objetos como unidades básicas para modelar dados e funcionalidades",
      "Uma linguagem de programação que usa apenas números para modelar dados e funcionalidades",
    ],
    topic: "Programação Orientada a Objetos",
    difficulty: "medium",
  },
];

const getRandomQuestion = (prevIds = []) => {
  const randomIndex = Math.floor(Math.random() * questions.length);

  const next = questions[randomIndex];

  return prevIds.includes(next.id) ? getRandomQuestion(prevIds) : next;
};

module.exports = {
  getRandomQuestion,
};
